export const GLOBAL_STORY_OPTIONS: Record<string, { text: string, emoji: string, translations: Record<string, string> }[]> = {
  characters: [
    { text: "Astronaut", emoji: "👨‍🚀", translations: { French: "Astronaute", Chinese: "宇航员", Korean: "우주비행사", Spanish: "Astronauta" } },
    { text: "Dragon", emoji: "🐉", translations: { French: "Dragon", Chinese: "龙", Korean: "용", Spanish: "Dragón" } },
    { text: "Robot", emoji: "🤖", translations: { French: "Robot", Chinese: "机器人", Korean: "로봇", Spanish: "Robot" } },
    { text: "Mermaid", emoji: "🧜‍♀️", translations: { French: "Sirène", Chinese: "美人鱼", Korean: "인어", Spanish: "Sirena" } },
    { text: "Detective", emoji: "🕵️‍♂️", translations: { French: "Détective", Chinese: "侦探", Korean: "탐정", Spanish: "Detective" } },
    { text: "Fairy", emoji: "🧚‍♀️", translations: { French: "Fée", Chinese: "仙女", Korean: "요정", Spanish: "Hada" } },
    { text: "Pirate", emoji: "🏴‍☠️", translations: { French: "Pirate", Chinese: "海盗", Korean: "해적", Spanish: "Pirata" } },
    { text: "Scientist", emoji: "🧑‍🔬", translations: { French: "Scientifique", Chinese: "科学家", Korean: "과학자", Spanish: "Científico" } },
    { text: "Knight", emoji: "🛡️", translations: { French: "Chevalier", Chinese: "骑士", Korean: "기사", Spanish: "Caballero" } },
    { text: "Wizard", emoji: "🧙‍♂️", translations: { French: "Sorcier", Chinese: "巫师", Korean: "마법사", Spanish: "Mago" } },
    { text: "Baker", emoji: "🧑‍🍳", translations: { French: "Boulanger", Chinese: "面包师", Korean: "제빵사", Spanish: "Panadero" } },
    { text: "Explorer", emoji: "🧭", translations: { French: "Explorateur", Chinese: "探险家", Korean: "탐험가", Spanish: "Explorador" } },
    { text: "Dinosaur", emoji: "🦖", translations: { French: "Dinosaure", Chinese: "恐龙", Korean: "공룡", Spanish: "Dinosaurio" } },
    { text: "Superhero", emoji: "🦸‍♂️", translations: { French: "Super-héros", Chinese: "超级英雄", Korean: "슈퍼히어로", Spanish: "Superhéroe" } },
    { text: "Gardener", emoji: "🧑‍🌾", translations: { French: "Jardinier", Chinese: "园丁", Korean: "정원사", Spanish: "Jardinero" } },
    { text: "Pilot", emoji: "🧑‍✈️", translations: { French: "Pilote", Chinese: "飞行员", Korean: "조종사", Spanish: "Piloto" } },
    { text: "Musician", emoji: "🧑‍🎤", translations: { French: "Musicien", Chinese: "音乐家", Korean: "음악가", Spanish: "Másico" } },
    { text: "Artist", emoji: "🧑‍🎨", translations: { French: "Artiste", Chinese: "艺术家", Korean: "예술가", Spanish: "Artista" } },
    { text: "Ninja", emoji: "🥷", translations: { French: "Ninja", Chinese: "忍者", Korean: "닌자", Spanish: "Ninja" } },
    { text: "Vet", emoji: "🧑‍⚕️", translations: { French: "Vétérinaire", Chinese: "兽医", Korean: "수의사", Spanish: "Veterinario" } },
    { text: "Firefighter", emoji: "🧑‍🚒", translations: { French: "Pompier", Chinese: "消防员", Korean: "소방관", Spanish: "Bombero" } },
    { text: "Chef", emoji: "👨‍🍳", translations: { French: "Chef", Chinese: "厨师", Korean: "요리사", Spanish: "Chef" } },
    { text: "Diver", emoji: "🤿", translations: { French: "Plongeur", Chinese: "潜水员", Korean: "다이버", Spanish: "Buceador" } },
    { text: "Inventor", emoji: "💡", translations: { French: "Inventeur", Chinese: "发明家", Korean: "발명가", Spanish: "Inventor" } }
  ],
  locations: [
    { text: "Moon", emoji: "🌙", translations: { French: "Lune", Chinese: "月亮", Korean: "달", Spanish: "Luna" } },
    { text: "Jungle", emoji: "🌴", translations: { French: "Jungle", Chinese: "丛林", Korean: "정글", Spanish: "Selva" } },
    { text: "Underwater City", emoji: "🌊", translations: { French: "Cité sous-marine", Chinese: "水下城市", Korean: "해저 도시", Spanish: "Ciudad submarina" } },
    { text: "Treehouse", emoji: "🏠", translations: { French: "Cabane dans les arbres", Chinese: "树屋", Korean: "나무집", Spanish: "Casa del árbol" } },
    { text: "Magic Forest", emoji: "🌲", translations: { French: "Forêt magique", Chinese: "魔法森林", Korean: "마법의 숲", Spanish: "Bosque mágico" } },
    { text: "Candy Land", emoji: "🍭", translations: { French: "Pays des bonbons", Chinese: "糖果乐园", Korean: "캔디 랜드", Spanish: "Tierra de caramelos" } },
    { text: "Castle", emoji: "🏰", translations: { French: "Château", Chinese: "城堡", Korean: "성", Spanish: "Castillo" } },
    { text: "Space Station", emoji: "🚀", translations: { French: "Station spatiale", Chinese: "空间站", Korean: "우주 정거장", Spanish: "Estación espacial" } },
    { text: "Desert Island", emoji: "🏝️", translations: { French: "Île déserte", Chinese: "荒岛", Korean: "무인도", Spanish: "Isla desierta" } },
    { text: "Snowy Mountain", emoji: "🏔️", translations: { French: "Montagne enneigée", Chinese: "雪山", Korean: "눈 덮인 산", Spanish: "Montaña nevada" } },
    { text: "Secret Garden", emoji: "🏡", translations: { French: "Jardin secret", Chinese: "秘密花园", Korean: "비밀 정원", Spanish: "Jardín secreto" } },
    { text: "Library", emoji: "📚", translations: { French: "Bibliothèque", Chinese: "图书馆", Korean: "도서관", Spanish: "Biblioteca" } },
    { text: "Museum", emoji: "🏛️", translations: { French: "Musée", Chinese: "博物馆", Korean: "박물관", Spanish: "Museo" } },
    { text: "Farm", emoji: "🚜", translations: { French: "Ferme", Chinese: "农场", Korean: "농장", Spanish: "Granja" } },
    { text: "Beach", emoji: "🏖️", translations: { French: "Plage", Chinese: "海滩", Korean: "해변", Spanish: "Playa" } },
    { text: "Volcano", emoji: "🌋", translations: { French: "Volcan", Chinese: "火山", Korean: "화산", Spanish: "Volcán" } },
    { text: "Cave", emoji: "🕳️", translations: { French: "Grotte", Chinese: "洞穴", Korean: "동굴", Spanish: "Cueva" } },
    { text: "Lighthouse", emoji: "🚨", translations: { French: "Phare", Chinese: "灯塔", Korean: "등대", Spanish: "Faro" } },
    { text: "Amusement Park", emoji: "🎡", translations: { French: "Parc d'attractions", Chinese: "游乐园", Korean: "놀이공원", Spanish: "Parque de atracciones" } },
    { text: "Planetarium", emoji: "🪐", translations: { French: "Planétarium", Chinese: "天文馆", Korean: "플라네타륨", Spanish: "Planetario" } },
    { text: "Aquarium", emoji: "🐠", translations: { French: "Aquarium", Chinese: "水族馆", Korean: "아쿠아리움", Spanish: "Acuario" } },
    { text: "Greenhouse", emoji: "🌿", translations: { French: "Serre", Chinese: "温室", Korean: "온실", Spanish: "Invernadero" } },
    { text: "Workshop", emoji: "🛠️", translations: { French: "Atelier", Chinese: "工作坊", Korean: "작업실", Spanish: "Taller" } },
    { text: "Cloud Kingdom", emoji: "☁️", translations: { French: "Royaume des nuages", Chinese: "云端王国", Korean: "구름 왕국", Spanish: "Reino de las nubes" } }
  ],
  values: [
    { text: "Kindness", emoji: "❤️", translations: { French: "Bonté", Chinese: "善良", Korean: "친절", Spanish: "Bondad" } },
    { text: "Courage", emoji: "🦁", translations: { French: "Courage", Chinese: "勇气", Korean: "용기", Spanish: "Coraje" } },
    { text: "Honesty", emoji: "💡", translations: { French: "Honnêteté", Chinese: "诚实", Korean: "정직", Spanish: "Honestidad" } },
    { text: "Friendship", emoji: "🤝", translations: { French: "Amitié", Chinese: "友谊", Korean: "우정", Spanish: "Amistad" } },
    { text: "Sharing", emoji: "🍰", translations: { French: "Partage", Chinese: "分享", Korean: "나눔", Spanish: "Compartir" } },
    { text: "Patience", emoji: "⏳", translations: { French: "Patience", Chinese: "耐心", Korean: "인내", Spanish: "Paciencia" } },
    { text: "Curiosity", emoji: "🔍", translations: { French: "Curiosité", Chinese: "好奇心", Korean: "호기심", Spanish: "Curiosidad" } },
    { text: "Teamwork", emoji: "🐜", translations: { French: "Travail d'équipe", Chinese: "团队合作", Korean: "팀워크", Spanish: "Trabajo en equipo" } },
    { text: "Respect", emoji: "🙇", translations: { French: "Respect", Chinese: "尊重", Korean: "존중", Spanish: "Respeto" } },
    { text: "Gratitude", emoji: "🙏", translations: { French: "Gratitude", Chinese: "感激", Korean: "감사", Spanish: "Gratitud" } },
    { text: "Perseverance", emoji: "🧗", translations: { French: "Persévérance", Chinese: "毅力", Korean: "인내심", Spanish: "Perseverancia" } },
    { text: "Forgiveness", emoji: "🕊️", translations: { French: "Pardon", Chinese: "宽恕", Korean: "용서", Spanish: "Perdón" } },
    { text: "Responsibility", emoji: "📋", translations: { French: "Responsabilité", Chinese: "责任", Korean: "책임", Spanish: "Responsabilidad" } },
    { text: "Empathy", emoji: "🫂", translations: { French: "Empathie", Chinese: "同理心", Korean: "공감", Spanish: "Empatía" } },
    { text: "Generosity", emoji: "🎁", translations: { French: "Générosité", Chinese: "慷慨", Korean: "관대함", Spanish: "Generosidad" } },
    { text: "Loyalty", emoji: "🐕", translations: { French: "Loyauté", Chinese: "忠诚", Korean: "충성", Spanish: "Lealtad" } },
    { text: "Creativity", emoji: "🎨", translations: { French: "Créativité", Chinese: "创造力", Korean: "창의성", Spanish: "Creatividad" } },
    { text: "Wisdom", emoji: "🦉", translations: { French: "Sagesse", Chinese: "智慧", Korean: "지혜", Spanish: "Sabiduría" } },
    { text: "Humility", emoji: "🌾", translations: { French: "Humilité", Chinese: "谦逊", Korean: "겸손", Spanish: "Humildad" } },
    { text: "Discipline", emoji: "🥋", translations: { French: "Discipline", Chinese: "纪律", Korean: "규율", Spanish: "Disciplina" } },
    { text: "Optimism", emoji: "☀️", translations: { French: "Optimisme", Chinese: "乐观", Korean: "낙관주의", Spanish: "Optimismo" } },
    { text: "Integrity", emoji: "💎", translations: { French: "Intégrité", Chinese: "正直", Korean: "진실성", Spanish: "Integridad" } },
    { text: "Compassion", emoji: "🩹", translations: { French: "Compassion", Chinese: "同情心", Korean: "동정심", Spanish: "Compasión" } },
    { text: "Determination", emoji: "🎯", translations: { French: "Détermination", Chinese: "决心", Korean: "결단력", Spanish: "Determinación" } }
  ]
};

